
public void clickBotonJugar(GButton source, GEvent event) { //_CODE_:botonJugar:652482:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:botonJugar:652482:

public void botonClickHistoria(GButton source, GEvent event) { //_CODE_:botonHistoria:564605:
  
} //_CODE_:botonHistoria:564605:

public void botonClickCreditos(GButton source, GEvent event) { //_CODE_:botonCreditos:523639:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:botonCreditos:523639:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  botonJugar = new GButton(this, 385, 245, 130, 30);
  botonJugar.setText("¡JUGAR!");
  botonJugar.setTextBold();
  botonJugar.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  botonJugar.addEventHandler(this, "clickBotonJugar");
  botonHistoria = new GButton(this, 385, 285, 130, 30);
  botonHistoria.setText("HISTORIA");
  botonHistoria.setTextBold();
  botonHistoria.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  botonHistoria.addEventHandler(this, "botonClickHistoria");
  botonCreditos = new GButton(this, 385, 325, 130, 30);
  botonCreditos.setText("CRÉDITOS");
  botonCreditos.setTextBold();
  botonCreditos.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  botonCreditos.addEventHandler(this, "botonClickCreditos");
}

// Variable declarations 
// autogenerated do not edit
GButton botonJugar; 
GButton botonHistoria; 
GButton botonCreditos; 